/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1;

import java.util.HashMap;
import java.util.Map;

import com.globalmiles.api.test1.models.*;

public class Configuration {
    /**
     * Current API environment
     */
    public static Environments environment = Environments.CLOUD;

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentMapper(Configuration.environment, server));
        Map<String, Object> parameters = new HashMap<String, Object>();
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.ENUM_DEFAULT);
    }
    
    /**
     * Base URLs by environments and server aliases 
     */

    private static String environmentMapper(Environments environments, Servers servers) {
		String url = "";
		if(environments.equals(Environments.CLOUD)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "https://test1.api.globalmiles.com";
		}
		return url;
	}
}
