/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1;

import com.globalmiles.api.test1.controllers.*;
import com.globalmiles.api.test1.http.client.HttpClient;

public class GlobalMilesAirlineAPIClient {
    /**
     * Singleton access to Members controller
     * @return	Returns the MembersController instance 
     */
    public MembersController getMembers() {
        return MembersController.getInstance();
    }

    /**
     * Singleton access to Flights controller
     * @return	Returns the FlightsController instance 
     */
    public FlightsController getFlights() {
        return FlightsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public GlobalMilesAirlineAPIClient() {
    }

}