/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Amount 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5177580482187099524L;
    private String currencyCode;
    private double value;
    /** GETTER
     * ISO 4217 currency code of the amount.
     */
    @JsonGetter("currency_code")
    public String getCurrencyCode ( ) { 
        return this.currencyCode;
    }
    
    /** SETTER
     * ISO 4217 currency code of the amount.
     */
    @JsonSetter("currency_code")
    public void setCurrencyCode (String value) { 
        this.currencyCode = value;
    }
 
    /** GETTER
     * A decimal value with two decimals in the string representation of amount.
     */
    @JsonGetter("value")
    public double getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * A decimal value with two decimals in the string representation of amount.
     */
    @JsonSetter("value")
    public void setValue (double value) { 
        this.value = value;
    }
 
}
 