/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class AwardMilesRules 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2432843462852073035L;
    private AwardTypeEnum awardType;
    private int baseRatio;
    private int checkinRatio;
    private int checkoutRatio;
    private int surveyRatio;
    /** GETTER
     * The type of the award base. The possible values are 'distance_based' and 'fare_based'.
     */
    @JsonGetter("award_type")
    public AwardTypeEnum getAwardType ( ) { 
        return this.awardType;
    }
    
    /** SETTER
     * The type of the award base. The possible values are 'distance_based' and 'fare_based'.
     */
    @JsonSetter("award_type")
    public void setAwardType (AwardTypeEnum value) { 
        this.awardType = value;
    }
 
    /** GETTER
     * The ratio for calculating base mile from distance or fare. Possible value is an integer between 1 and 100.
     */
    @JsonGetter("base_ratio")
    public int getBaseRatio ( ) { 
        return this.baseRatio;
    }
    
    /** SETTER
     * The ratio for calculating base mile from distance or fare. Possible value is an integer between 1 and 100.
     */
    @JsonSetter("base_ratio")
    public void setBaseRatio (int value) { 
        this.baseRatio = value;
    }
 
    /** GETTER
     * The additional mile ratio for a check-in operation. Possible value as an integer between 0 and 100.
     */
    @JsonGetter("checkin_ratio")
    public int getCheckinRatio ( ) { 
        return this.checkinRatio;
    }
    
    /** SETTER
     * The additional mile ratio for a check-in operation. Possible value as an integer between 0 and 100.
     */
    @JsonSetter("checkin_ratio")
    public void setCheckinRatio (int value) { 
        this.checkinRatio = value;
    }
 
    /** GETTER
     * The additional mile ratio for a check-out operation. Possible value as an integer between 0 and 100.
     */
    @JsonGetter("checkout_ratio")
    public int getCheckoutRatio ( ) { 
        return this.checkoutRatio;
    }
    
    /** SETTER
     * The additional mile ratio for a check-out operation. Possible value as an integer between 0 and 100.
     */
    @JsonSetter("checkout_ratio")
    public void setCheckoutRatio (int value) { 
        this.checkoutRatio = value;
    }
 
    /** GETTER
     * The additional mile ratio for a survey. Possible value as an integer between 0 and 100.
     */
    @JsonGetter("survey_ratio")
    public int getSurveyRatio ( ) { 
        return this.surveyRatio;
    }
    
    /** SETTER
     * The additional mile ratio for a survey. Possible value as an integer between 0 and 100.
     */
    @JsonSetter("survey_ratio")
    public void setSurveyRatio (int value) { 
        this.surveyRatio = value;
    }
 
}
