/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum AwardTypeEnum {
    DISTANCE_BASED, //TODO: Write general description for this element
    FAIR_BASED; //TODO: Write general description for this element

    private static TreeMap<String, AwardTypeEnum> valueMap = new TreeMap<String, AwardTypeEnum>();
    private String value;

    static {
        DISTANCE_BASED.value = "distance_based";
        FAIR_BASED.value = "fair_based";

        valueMap.put("distance_based", DISTANCE_BASED);
        valueMap.put("fair_based", FAIR_BASED);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AwardTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AwardTypeEnum values to list of string values
     * @param toConvert The list of AwardTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<AwardTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (AwardTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 