/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class AwardMilesRulesBuilder {
    //the instance to build
    private AwardMilesRules awardMilesRules;

    /**
     * Default constructor to initialize the instance
     */
    public AwardMilesRulesBuilder() {
        awardMilesRules = new AwardMilesRules();
    }

    /**
     * The type of the award base. The possible values are 'distance_based' and 'fare_based'.
     */
    public AwardMilesRulesBuilder awardType(AwardTypeEnum awardType) {
        awardMilesRules.setAwardType(awardType);
        return this;
    }

    /**
     * The ratio for calculating base mile from distance or fare. Possible value is an integer between 1 and 100.
     */
    public AwardMilesRulesBuilder baseRatio(int baseRatio) {
        awardMilesRules.setBaseRatio(baseRatio);
        return this;
    }

    /**
     * The additional mile ratio for a check-in operation. Possible value as an integer between 0 and 100.
     */
    public AwardMilesRulesBuilder checkinRatio(int checkinRatio) {
        awardMilesRules.setCheckinRatio(checkinRatio);
        return this;
    }

    /**
     * The additional mile ratio for a check-out operation. Possible value as an integer between 0 and 100.
     */
    public AwardMilesRulesBuilder checkoutRatio(int checkoutRatio) {
        awardMilesRules.setCheckoutRatio(checkoutRatio);
        return this;
    }

    /**
     * The additional mile ratio for a survey. Possible value as an integer between 0 and 100.
     */
    public AwardMilesRulesBuilder surveyRatio(int surveyRatio) {
        awardMilesRules.setSurveyRatio(surveyRatio);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AwardMilesRules build() {
        return awardMilesRules;
    }
}