/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CabinTypeEnum {
    UNKNOWN, //Unknown
    DISCOUNT_ECONOMY, //Discount Economy
    ECONOMY, //Economy
    FULL_ECONOMY, //Full Economy
    PREMIUM_ECONOMY, //Premium Economy
    DISCOUNT_BUSINESS, //Discount Business
    BUSINESS, //Business
    PREMIUM_BUSINESS, //Premium Business
    FIRST, //First
    PREMIUM_FIRST; //Premium First

    private static TreeMap<String, CabinTypeEnum> valueMap = new TreeMap<String, CabinTypeEnum>();
    private String value;

    static {
        UNKNOWN.value = "unknown";
        DISCOUNT_ECONOMY.value = "discount_economy";
        ECONOMY.value = "economy";
        FULL_ECONOMY.value = "full_economy";
        PREMIUM_ECONOMY.value = "premium_economy";
        DISCOUNT_BUSINESS.value = "discount_business";
        BUSINESS.value = "business";
        PREMIUM_BUSINESS.value = "premium_business";
        FIRST.value = "first";
        PREMIUM_FIRST.value = "premium_first";

        valueMap.put("unknown", UNKNOWN);
        valueMap.put("discount_economy", DISCOUNT_ECONOMY);
        valueMap.put("economy", ECONOMY);
        valueMap.put("full_economy", FULL_ECONOMY);
        valueMap.put("premium_economy", PREMIUM_ECONOMY);
        valueMap.put("discount_business", DISCOUNT_BUSINESS);
        valueMap.put("business", BUSINESS);
        valueMap.put("premium_business", PREMIUM_BUSINESS);
        valueMap.put("first", FIRST);
        valueMap.put("premium_first", PREMIUM_FIRST);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CabinTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CabinTypeEnum values to list of string values
     * @param toConvert The list of CabinTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CabinTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CabinTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 