/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ExtraInfoTypeEnum {
    NATIONALITY, //Nationality
    NATIONAL_ID_NUMBER, //National ID Number
    LANGUAGE, //Language
    GENDER, //Gender
    BIRTHDAY, //Birthday
    ACADEMIC_TITLE, //Academic Title
    ADDRESS, //Address
    COUNTRY, //Country
    CITY, //City
    AREA, //Area
    ZIP_CODE, //Zip Code
    PASSWORD; //Password

    private static TreeMap<String, ExtraInfoTypeEnum> valueMap = new TreeMap<String, ExtraInfoTypeEnum>();
    private String value;

    static {
        NATIONALITY.value = "nationality";
        NATIONAL_ID_NUMBER.value = "national_id_number";
        LANGUAGE.value = "language";
        GENDER.value = "gender";
        BIRTHDAY.value = "birthday";
        ACADEMIC_TITLE.value = "academic_title";
        ADDRESS.value = "address";
        COUNTRY.value = "country";
        CITY.value = "city";
        AREA.value = "area";
        ZIP_CODE.value = "zip_code";
        PASSWORD.value = "password";

        valueMap.put("nationality", NATIONALITY);
        valueMap.put("national_id_number", NATIONAL_ID_NUMBER);
        valueMap.put("language", LANGUAGE);
        valueMap.put("gender", GENDER);
        valueMap.put("birthday", BIRTHDAY);
        valueMap.put("academic_title", ACADEMIC_TITLE);
        valueMap.put("address", ADDRESS);
        valueMap.put("country", COUNTRY);
        valueMap.put("city", CITY);
        valueMap.put("area", AREA);
        valueMap.put("zip_code", ZIP_CODE);
        valueMap.put("password", PASSWORD);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ExtraInfoTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ExtraInfoTypeEnum values to list of string values
     * @param toConvert The list of ExtraInfoTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ExtraInfoTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ExtraInfoTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 