/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum FlightStatusTypeEnum {
    USED, //Used
    UNUSED, //Unused
    REISSUED; //Reissued

    private static TreeMap<String, FlightStatusTypeEnum> valueMap = new TreeMap<String, FlightStatusTypeEnum>();
    private String value;

    static {
        USED.value = "used";
        UNUSED.value = "unused";
        REISSUED.value = "reissued";

        valueMap.put("used", USED);
        valueMap.put("unused", UNUSED);
        valueMap.put("reissued", REISSUED);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static FlightStatusTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of FlightStatusTypeEnum values to list of string values
     * @param toConvert The list of FlightStatusTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<FlightStatusTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (FlightStatusTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 