/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class FlightMinBuilder {
    //the instance to build
    private FlightMin flightMin;

    /**
     * Default constructor to initialize the instance
     */
    public FlightMinBuilder() {
        flightMin = new FlightMin();
    }

    /**
     * Passenger name record of the flight.
     */
    public FlightMinBuilder pnr(String pnr) {
        flightMin.setPnr(pnr);
        return this;
    }

    /**
     * Ticket number of the passenger.
     */
    public FlightMinBuilder ticketNumber(String ticketNumber) {
        flightMin.setTicketNumber(ticketNumber);
        return this;
    }

    /**
     * Number of the flight.
     */
    public FlightMinBuilder flightNumber(String flightNumber) {
        flightMin.setFlightNumber(flightNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FlightMin build() {
        return flightMin;
    }
}