/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FlightSimple 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5402190731108908352L;
    private String airline;
    private String pnr;
    private String departureDate;
    private String departureAirport;
    private String arrivalAirport;
    /** GETTER
     * IATA code for airline company.
     */
    @JsonGetter("airline")
    public String getAirline ( ) { 
        return this.airline;
    }
    
    /** SETTER
     * IATA code for airline company.
     */
    @JsonSetter("airline")
    public void setAirline (String value) { 
        this.airline = value;
    }
 
    /** GETTER
     * Passenger name record of the flight.
     */
    @JsonGetter("pnr")
    public String getPnr ( ) { 
        return this.pnr;
    }
    
    /** SETTER
     * Passenger name record of the flight.
     */
    @JsonSetter("pnr")
    public void setPnr (String value) { 
        this.pnr = value;
    }
 
    /** GETTER
     * ISO 8601 date for departure time.
     */
    @JsonGetter("departure_date")
    public String getDepartureDate ( ) { 
        return this.departureDate;
    }
    
    /** SETTER
     * ISO 8601 date for departure time.
     */
    @JsonSetter("departure_date")
    public void setDepartureDate (String value) { 
        this.departureDate = value;
    }
 
    /** GETTER
     * IATA code for the departure airport.
     */
    @JsonGetter("departure_airport")
    public String getDepartureAirport ( ) { 
        return this.departureAirport;
    }
    
    /** SETTER
     * IATA code for the departure airport.
     */
    @JsonSetter("departure_airport")
    public void setDepartureAirport (String value) { 
        this.departureAirport = value;
    }
 
    /** GETTER
     * IATA code for the  arrival airport.
     */
    @JsonGetter("arrival_airport")
    public String getArrivalAirport ( ) { 
        return this.arrivalAirport;
    }
    
    /** SETTER
     * IATA code for the  arrival airport.
     */
    @JsonSetter("arrival_airport")
    public void setArrivalAirport (String value) { 
        this.arrivalAirport = value;
    }
 
}
 