/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FlightStatusRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5024131227836996713L;
    private PassengerMin passenger;
    private FlightMin flight;
    /** GETTER
     * A complex object for representing passenger.
     */
    @JsonGetter("passenger")
    public PassengerMin getPassenger ( ) { 
        return this.passenger;
    }
    
    /** SETTER
     * A complex object for representing passenger.
     */
    @JsonSetter("passenger")
    public void setPassenger (PassengerMin value) { 
        this.passenger = value;
    }
 
    /** GETTER
     * A complex object for flight.
     */
    @JsonGetter("flight")
    public FlightMin getFlight ( ) { 
        return this.flight;
    }
    
    /** SETTER
     * A complex object for flight.
     */
    @JsonSetter("flight")
    public void setFlight (FlightMin value) { 
        this.flight = value;
    }
 
}
 