/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class FlightMin 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7917725996735256606L;
    private String pnr;
    private String ticketNumber;
    private String flightNumber;
    /** GETTER
     * Passenger name record of the flight.
     */
    @JsonGetter("pnr")
    public String getPnr ( ) { 
        return this.pnr;
    }
    
    /** SETTER
     * Passenger name record of the flight.
     */
    @JsonSetter("pnr")
    public void setPnr (String value) { 
        this.pnr = value;
    }
 
    /** GETTER
     * Ticket number of the passenger.
     */
    @JsonGetter("ticket_number")
    public String getTicketNumber ( ) { 
        return this.ticketNumber;
    }
    
    /** SETTER
     * Ticket number of the passenger.
     */
    @JsonSetter("ticket_number")
    public void setTicketNumber (String value) { 
        this.ticketNumber = value;
    }
 
    /** GETTER
     * Number of the flight.
     */
    @JsonGetter("flight_number")
    public String getFlightNumber ( ) { 
        return this.flightNumber;
    }
    
    /** SETTER
     * Number of the flight.
     */
    @JsonSetter("flight_number")
    public void setFlightNumber (String value) { 
        this.flightNumber = value;
    }
 
}
