/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class FlightMaxBuilder {
    //the instance to build
    private FlightMax flightMax;

    /**
     * Default constructor to initialize the instance
     */
    public FlightMaxBuilder() {
        flightMax = new FlightMax();
    }

    /**
     * IATA code for airline company.
     */
    public FlightMaxBuilder airline(String airline) {
        flightMax.setAirline(airline);
        return this;
    }

    /**
     * Cabin type of the flight.
     */
    public FlightMaxBuilder cabinType(String cabinType) {
        flightMax.setCabinType(cabinType);
        return this;
    }

    /**
     * Number of the flight.
     */
    public FlightMaxBuilder flightNumber(String flightNumber) {
        flightMax.setFlightNumber(flightNumber);
        return this;
    }

    /**
     * Passenger name record of the flight.
     */
    public FlightMaxBuilder pnr(String pnr) {
        flightMax.setPnr(pnr);
        return this;
    }

    /**
     * Ticket number of the passenger.
     */
    public FlightMaxBuilder ticketNumber(String ticketNumber) {
        flightMax.setTicketNumber(ticketNumber);
        return this;
    }

    /**
     * IATA code for the departure airport.
     */
    public FlightMaxBuilder departureAirport(String departureAirport) {
        flightMax.setDepartureAirport(departureAirport);
        return this;
    }

    /**
     * IATA code for the  arrival airport.
     */
    public FlightMaxBuilder arrivalAirport(String arrivalAirport) {
        flightMax.setArrivalAirport(arrivalAirport);
        return this;
    }

    /**
     * ISO 8601 date and time in UTC for departure time.
     */
    public FlightMaxBuilder departureDateTime(String departureDateTime) {
        flightMax.setDepartureDateTime(departureDateTime);
        return this;
    }

    /**
     * ISO 8601 date and time in UTC for arrival time.
     */
    public FlightMaxBuilder arrivalDateTime(String arrivalDateTime) {
        flightMax.setArrivalDateTime(arrivalDateTime);
        return this;
    }

    /**
     * A complex object for the amount of the flight including currency and value.
     */
    public FlightMaxBuilder totalAmount(Amount totalAmount) {
        flightMax.setTotalAmount(totalAmount);
        return this;
    }

    /**
     * The distance between departure and arrival airports.
     */
    public FlightMaxBuilder distance(Integer distance) {
        flightMax.setDistance(distance);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FlightMax build() {
        return flightMax;
    }
}