/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class FlightStatusResponseBuilder 
        extends ResponseBuilder {
    //the instance to build
    private FlightStatusResponse flightStatusResponse;

    /**
     * Default constructor to initialize the instance
     */
    public FlightStatusResponseBuilder() {
        flightStatusResponse = new FlightStatusResponse();
    }

    /**
     * The final status of flight. The possible values are 'used', 'unused' and 'reissued'. For the reissued tickets the following new flight information must provided.
     */
    public FlightStatusResponseBuilder flightStatus(FlightStatusTypeEnum flightStatus) {
        flightStatusResponse.setFlightStatus(flightStatus);
        return this;
    }

    /**
     * A complex for the flight. It is only accepted for reissued status.
     */
    public FlightStatusResponseBuilder flight(FlightMax flight) {
        flightStatusResponse.setFlight(flight);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FlightStatusResponse build() {
        return flightStatusResponse;
    }
}