/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class FlightCreateRequestBuilder {
    //the instance to build
    private FlightCreateRequest flightCreateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public FlightCreateRequestBuilder() {
        flightCreateRequest = new FlightCreateRequest();
    }

    /**
     * A complex object for definition of the award mile calculation logic.
     */
    public FlightCreateRequestBuilder awardMilesRules(AwardMilesRules awardMilesRules) {
        flightCreateRequest.setAwardMilesRules(awardMilesRules);
        return this;
    }

    /**
     * A complex object for representing a passenger.
     */
    public FlightCreateRequestBuilder passenger(PassengerMax passenger) {
        flightCreateRequest.setPassenger(passenger);
        return this;
    }

    /**
     * Routing type of the flights.
     */
    public FlightCreateRequestBuilder routingType(RoutingTypeEnum routingType) {
        flightCreateRequest.setRoutingType(routingType);
        return this;
    }

    /**
     * An array of flights. We are expecting one flight for one way trip and two flights for round trip.
     */
    public FlightCreateRequestBuilder flights(List<FlightMax> flights) {
        flightCreateRequest.setFlights(flights);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FlightCreateRequest build() {
        return flightCreateRequest;
    }
}