/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class FlightSimpleBuilder {
    //the instance to build
    private FlightSimple flightSimple;

    /**
     * Default constructor to initialize the instance
     */
    public FlightSimpleBuilder() {
        flightSimple = new FlightSimple();
    }

    /**
     * IATA code for airline company.
     */
    public FlightSimpleBuilder airline(String airline) {
        flightSimple.setAirline(airline);
        return this;
    }

    /**
     * Passenger name record of the flight.
     */
    public FlightSimpleBuilder pnr(String pnr) {
        flightSimple.setPnr(pnr);
        return this;
    }

    /**
     * ISO 8601 date for departure time.
     */
    public FlightSimpleBuilder departureDate(String departureDate) {
        flightSimple.setDepartureDate(departureDate);
        return this;
    }

    /**
     * IATA code for the departure airport.
     */
    public FlightSimpleBuilder departureAirport(String departureAirport) {
        flightSimple.setDepartureAirport(departureAirport);
        return this;
    }

    /**
     * IATA code for the  arrival airport.
     */
    public FlightSimpleBuilder arrivalAirport(String arrivalAirport) {
        flightSimple.setArrivalAirport(arrivalAirport);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FlightSimple build() {
        return flightSimple;
    }
}