/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum GenderTypeEnum {
    MALE, //Male
    FEMALE, //Female
    UNKNOWN; //Unknown

    private static TreeMap<String, GenderTypeEnum> valueMap = new TreeMap<String, GenderTypeEnum>();
    private String value;

    static {
        MALE.value = "male";
        FEMALE.value = "female";
        UNKNOWN.value = "unknown";

        valueMap.put("male", MALE);
        valueMap.put("female", FEMALE);
        valueMap.put("unknown", UNKNOWN);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static GenderTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of GenderTypeEnum values to list of string values
     * @param toConvert The list of GenderTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<GenderTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (GenderTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 