/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MemberSearchResponse 
        extends Response {
    private static final long serialVersionUID = 4925448670785026358L;
    private CardTypeEnum cardType;
    private int baseMiles;
    private int promoMiles;
    /** GETTER
     * Type of miles card.
     */
    @JsonGetter("card_type")
    public CardTypeEnum getCardType ( ) { 
        return this.cardType;
    }
    
    /** SETTER
     * Type of miles card.
     */
    @JsonSetter("card_type")
    public void setCardType (CardTypeEnum value) { 
        this.cardType = value;
    }
 
    /** GETTER
     * Value of current miles.
     */
    @JsonGetter("base_miles")
    public int getBaseMiles ( ) { 
        return this.baseMiles;
    }
    
    /** SETTER
     * Value of current miles.
     */
    @JsonSetter("base_miles")
    public void setBaseMiles (int value) { 
        this.baseMiles = value;
    }
 
    /** GETTER
     * Value of status miles.
     */
    @JsonGetter("promo_miles")
    public int getPromoMiles ( ) { 
        return this.promoMiles;
    }
    
    /** SETTER
     * Value of status miles.
     */
    @JsonSetter("promo_miles")
    public void setPromoMiles (int value) { 
        this.promoMiles = value;
    }
 
}
 