/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MemberSearchRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2998995032619658128L;
    private String ffpNumber;
    private String firstName;
    private String lastName;
    /** GETTER
     * FFP number of member
     */
    @JsonGetter("ffp_number")
    public String getFfpNumber ( ) { 
        return this.ffpNumber;
    }
    
    /** SETTER
     * FFP number of member
     */
    @JsonSetter("ffp_number")
    public void setFfpNumber (String value) { 
        this.ffpNumber = value;
    }
 
    /** GETTER
     * First name
     */
    @JsonGetter("first_name")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * First name
     */
    @JsonSetter("first_name")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * Last name
     */
    @JsonGetter("last_name")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * Last name
     */
    @JsonSetter("last_name")
    public void setLastName (String value) { 
        this.lastName = value;
    }
 
}
