/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class MemberSearchResponseBuilder 
        extends ResponseBuilder {
    //the instance to build
    private MemberSearchResponse memberSearchResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MemberSearchResponseBuilder() {
        memberSearchResponse = new MemberSearchResponse();
    }

    /**
     * Type of tiers.
     */
    public MemberSearchResponseBuilder tierType(TierTypeEnum tierType) {
        memberSearchResponse.setTierType(tierType);
        return this;
    }

    /**
     * Value of current miles.
     */
    public MemberSearchResponseBuilder baseMiles(int baseMiles) {
        memberSearchResponse.setBaseMiles(baseMiles);
        return this;
    }

    /**
     * Value of status miles.
     */
    public MemberSearchResponseBuilder promoMiles(int promoMiles) {
        memberSearchResponse.setPromoMiles(promoMiles);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MemberSearchResponse build() {
        return memberSearchResponse;
    }
}