/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MemberSearchResponse 
        extends Response {
    private static final long serialVersionUID = 7871918662113294984L;
    private TierTypeEnum tierType;
    private int baseMiles;
    private int promoMiles;
    /** GETTER
     * Type of tiers.
     */
    @JsonGetter("tier_type")
    public TierTypeEnum getTierType ( ) { 
        return this.tierType;
    }
    
    /** SETTER
     * Type of tiers.
     */
    @JsonSetter("tier_type")
    public void setTierType (TierTypeEnum value) { 
        this.tierType = value;
    }
 
    /** GETTER
     * Value of current miles.
     */
    @JsonGetter("base_miles")
    public int getBaseMiles ( ) { 
        return this.baseMiles;
    }
    
    /** SETTER
     * Value of current miles.
     */
    @JsonSetter("base_miles")
    public void setBaseMiles (int value) { 
        this.baseMiles = value;
    }
 
    /** GETTER
     * Value of status miles.
     */
    @JsonGetter("promo_miles")
    public int getPromoMiles ( ) { 
        return this.promoMiles;
    }
    
    /** SETTER
     * Value of status miles.
     */
    @JsonSetter("promo_miles")
    public void setPromoMiles (int value) { 
        this.promoMiles = value;
    }
 
}
