/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class MemberSearchRequestBuilder {
    //the instance to build
    private MemberSearchRequest memberSearchRequest;

    /**
     * Default constructor to initialize the instance
     */
    public MemberSearchRequestBuilder() {
        memberSearchRequest = new MemberSearchRequest();
    }

    /**
     * FFP number of member
     */
    public MemberSearchRequestBuilder ffpNumber(String ffpNumber) {
        memberSearchRequest.setFfpNumber(ffpNumber);
        return this;
    }

    /**
     * First name
     */
    public MemberSearchRequestBuilder firstName(String firstName) {
        memberSearchRequest.setFirstName(firstName);
        return this;
    }

    /**
     * Last name
     */
    public MemberSearchRequestBuilder lastName(String lastName) {
        memberSearchRequest.setLastName(lastName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MemberSearchRequest build() {
        return memberSearchRequest;
    }
}