/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NewMemberResponse 
        extends Response {
    private static final long serialVersionUID = 4835272385482629005L;
    private String ffpNumber;
    private CardTypeEnum cardType;
    private List<ExtraInfoTypeEnum> needExtraInfo;
    /** GETTER
     * Card number of frequent flyer.
     */
    @JsonGetter("ffp_number")
    public String getFfpNumber ( ) { 
        return this.ffpNumber;
    }
    
    /** SETTER
     * Card number of frequent flyer.
     */
    @JsonSetter("ffp_number")
    public void setFfpNumber (String value) { 
        this.ffpNumber = value;
    }
 
    /** GETTER
     * Type of the miles card.
     */
    @JsonGetter("card_type")
    public CardTypeEnum getCardType ( ) { 
        return this.cardType;
    }
    
    /** SETTER
     * Type of the miles card.
     */
    @JsonSetter("card_type")
    public void setCardType (CardTypeEnum value) { 
        this.cardType = value;
    }
 
    /** GETTER
     * If the provided information is not enough to create a ffp member, this field can use to get new information. The possible values are language, gender, birthday, nationality, national_id_number, academic_title, address, country, city, area, zip_code, password. We will collect the additional information from user and will enhance the first request and will send it again.
     */
    @JsonGetter("need_extra_info")
    public List<ExtraInfoTypeEnum> getNeedExtraInfo ( ) { 
        return this.needExtraInfo;
    }
    
    /** SETTER
     * If the provided information is not enough to create a ffp member, this field can use to get new information. The possible values are language, gender, birthday, nationality, national_id_number, academic_title, address, country, city, area, zip_code, password. We will collect the additional information from user and will enhance the first request and will send it again.
     */
    @JsonSetter("need_extra_info")
    public void setNeedExtraInfo (List<ExtraInfoTypeEnum> value) { 
        this.needExtraInfo = value;
    }
 
}
 