/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NewMemberRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4651904165541955099L;
    private User user;
    private FlightSimple flight;
    /** GETTER
     * A complex object for representing a user.
     */
    @JsonGetter("user")
    public User getUser ( ) { 
        return this.user;
    }
    
    /** SETTER
     * A complex object for representing a user.
     */
    @JsonSetter("user")
    public void setUser (User value) { 
        this.user = value;
    }
 
    /** GETTER
     * A complex object for flight.
     */
    @JsonGetter("flight")
    public FlightSimple getFlight ( ) { 
        return this.flight;
    }
    
    /** SETTER
     * A complex object for flight.
     */
    @JsonSetter("flight")
    public void setFlight (FlightSimple value) { 
        this.flight = value;
    }
 
}
 