/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class NewMemberRequestBuilder {
    //the instance to build
    private NewMemberRequest newMemberRequest;

    /**
     * Default constructor to initialize the instance
     */
    public NewMemberRequestBuilder() {
        newMemberRequest = new NewMemberRequest();
    }

    /**
     * A complex object for representing a user.
     */
    public NewMemberRequestBuilder user(User user) {
        newMemberRequest.setUser(user);
        return this;
    }

    /**
     * A complex object for flight.
     */
    public NewMemberRequestBuilder flight(FlightSimple flight) {
        newMemberRequest.setFlight(flight);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NewMemberRequest build() {
        return newMemberRequest;
    }
}