/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class NewMemberResponseBuilder 
        extends ResponseBuilder {
    //the instance to build
    private NewMemberResponse newMemberResponse;

    /**
     * Default constructor to initialize the instance
     */
    public NewMemberResponseBuilder() {
        newMemberResponse = new NewMemberResponse();
    }

    /**
     * Card number of frequent flyer.
     */
    public NewMemberResponseBuilder ffpNumber(String ffpNumber) {
        newMemberResponse.setFfpNumber(ffpNumber);
        return this;
    }

    /**
     * Type of tiers.
     */
    public NewMemberResponseBuilder tierType(TierTypeEnum tierType) {
        newMemberResponse.setTierType(tierType);
        return this;
    }

    /**
     * If the provided information is not enough to create a ffp member, this field can use to get new information. The possible values are language, gender, birthday, nationality, national_id_number, academic_title, address, country, city, area, zip_code, password. We will collect the additional information from user and will enhance the first request and will send it again.
     */
    public NewMemberResponseBuilder needExtraInfo(List<ExtraInfoTypeEnum> needExtraInfo) {
        newMemberResponse.setNeedExtraInfo(needExtraInfo);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NewMemberResponse build() {
        return newMemberResponse;
    }
}