/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PassengerMin 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4771701973606740569L;
    private String firstName;
    private String lastName;
    private String mobile;
    private String email;
    /** GETTER
     * First name of the passenger. Maximum length is 40 characters.
     */
    @JsonGetter("first_name")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * First name of the passenger. Maximum length is 40 characters.
     */
    @JsonSetter("first_name")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * Last name of the passenger. Maximum length is 40 characters.
     */
    @JsonGetter("last_name")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * Last name of the passenger. Maximum length is 40 characters.
     */
    @JsonSetter("last_name")
    public void setLastName (String value) { 
        this.lastName = value;
    }
 
    /** GETTER
     * Mobile phone number of the passenger. It is a unique identifier for passengers in the system. The format is E.164.
     */
    @JsonGetter("mobile")
    public String getMobile ( ) { 
        return this.mobile;
    }
    
    /** SETTER
     * Mobile phone number of the passenger. It is a unique identifier for passengers in the system. The format is E.164.
     */
    @JsonSetter("mobile")
    public void setMobile (String value) { 
        this.mobile = value;
    }
 
    /** GETTER
     * Email address of the passenger.
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * Email address of the passenger.
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
}
 