/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class PassengerMinBuilder {
    //the instance to build
    private PassengerMin passengerMin;

    /**
     * Default constructor to initialize the instance
     */
    public PassengerMinBuilder() {
        passengerMin = new PassengerMin();
    }

    /**
     * First name of the passenger. Maximum length is 40 characters.
     */
    public PassengerMinBuilder firstName(String firstName) {
        passengerMin.setFirstName(firstName);
        return this;
    }

    /**
     * Last name of the passenger. Maximum length is 40 characters.
     */
    public PassengerMinBuilder lastName(String lastName) {
        passengerMin.setLastName(lastName);
        return this;
    }

    /**
     * Mobile phone number of the passenger. It is a unique identifier for passengers in the system. The format is E.164.
     */
    public PassengerMinBuilder mobile(String mobile) {
        passengerMin.setMobile(mobile);
        return this;
    }

    /**
     * Email address of the passenger.
     */
    public PassengerMinBuilder email(String email) {
        passengerMin.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PassengerMin build() {
        return passengerMin;
    }
}