/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class PassengerMaxBuilder {
    //the instance to build
    private PassengerMax passengerMax;

    /**
     * Default constructor to initialize the instance
     */
    public PassengerMaxBuilder() {
        passengerMax = new PassengerMax();
    }

    /**
     * First name of the passenger. Maximum length is 40 characters.
     */
    public PassengerMaxBuilder firstName(String firstName) {
        passengerMax.setFirstName(firstName);
        return this;
    }

    /**
     * Last name of the passenger. Maximum length is 40 characters.
     */
    public PassengerMaxBuilder lastName(String lastName) {
        passengerMax.setLastName(lastName);
        return this;
    }

    /**
     * Mobile phone number of the passenger. It is a unique identifier for passengers in the system. The format is E.164.
     */
    public PassengerMaxBuilder mobile(String mobile) {
        passengerMax.setMobile(mobile);
        return this;
    }

    /**
     * Email address of the passenger.
     */
    public PassengerMaxBuilder email(String email) {
        passengerMax.setEmail(email);
        return this;
    }

    /**
     * The language of the passenger. Possible values are 'en' and 'tr'. Default value is 'en'.
     */
    public PassengerMaxBuilder language(LanguageTypeEnum language) {
        passengerMax.setLanguage(language);
        return this;
    }

    /**
     * Gender of the passenger. The possible values are 'female', 'male' or 'unknown'.
     */
    public PassengerMaxBuilder gender(GenderTypeEnum gender) {
        passengerMax.setGender(gender);
        return this;
    }

    /**
     * Birthday of the passenger. The possible values are a date with YYYYMMDD formatted or null.
     */
    public PassengerMaxBuilder birthday(String birthday) {
        passengerMax.setBirthday(birthday);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PassengerMax build() {
        return passengerMax;
    }
}