/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum TierTypeEnum {
    UNKNOWN, //Unknown
    BASIC, //Basic
    TIER1, //Red
    TIER2, //Silver
    TIER3, //Gold
    TIER4, //Platinum
    TIER5, //Diamond
    TIER6; //Corparate

    private static TreeMap<String, TierTypeEnum> valueMap = new TreeMap<String, TierTypeEnum>();
    private String value;

    static {
        UNKNOWN.value = "unknown";
        BASIC.value = "basic";
        TIER1.value = "tier1";
        TIER2.value = "tier2";
        TIER3.value = "tier3";
        TIER4.value = "tier4";
        TIER5.value = "tier5";
        TIER6.value = "tier6";

        valueMap.put("unknown", UNKNOWN);
        valueMap.put("basic", BASIC);
        valueMap.put("tier1", TIER1);
        valueMap.put("tier2", TIER2);
        valueMap.put("tier3", TIER3);
        valueMap.put("tier4", TIER4);
        valueMap.put("tier5", TIER5);
        valueMap.put("tier6", TIER6);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TierTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TierTypeEnum values to list of string values
     * @param toConvert The list of TierTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<TierTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (TierTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 