/*
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.globalmiles.api.test1.models;

import java.util.*;

public class UserBuilder {
    //the instance to build
    private User user;

    /**
     * Default constructor to initialize the instance
     */
    public UserBuilder() {
        user = new User();
    }

    /**
     * First name of the user. Maximum length is 40 characters.
     */
    public UserBuilder firstName(String firstName) {
        user.setFirstName(firstName);
        return this;
    }

    /**
     * Last name of the user. Maximum length is 40 characters.
     */
    public UserBuilder lastName(String lastName) {
        user.setLastName(lastName);
        return this;
    }

    /**
     * Mobile phone number of the user It is a unique identifier for users in the system. The format is E.164.
     */
    public UserBuilder mobile(String mobile) {
        user.setMobile(mobile);
        return this;
    }

    /**
     * Email address of the user.
     */
    public UserBuilder email(String email) {
        user.setEmail(email);
        return this;
    }

    /**
     * The language of the user. Possible values are 'en' and 'tr'.
     */
    public UserBuilder language(LanguageTypeEnum language) {
        user.setLanguage(language);
        return this;
    }

    /**
     * Gender of the user. The possible values are 'female', 'male' or 'unknown'.
     */
    public UserBuilder gender(GenderTypeEnum gender) {
        user.setGender(gender);
        return this;
    }

    /**
     * Birthday of the user. The possible values are a date with YYYYMMDD formatted or null.
     */
    public UserBuilder birthday(String birthday) {
        user.setBirthday(birthday);
        return this;
    }

    /**
     * Nationality
     */
    public UserBuilder nationality(String nationality) {
        user.setNationality(nationality);
        return this;
    }

    /**
     * National ID Number
     */
    public UserBuilder nationalIdNumber(String nationalIdNumber) {
        user.setNationalIdNumber(nationalIdNumber);
        return this;
    }

    /**
     * Academic Title
     */
    public UserBuilder academicTitle(String academicTitle) {
        user.setAcademicTitle(academicTitle);
        return this;
    }

    /**
     * Address
     */
    public UserBuilder address(String address) {
        user.setAddress(address);
        return this;
    }

    /**
     * Country
     */
    public UserBuilder country(String country) {
        user.setCountry(country);
        return this;
    }

    /**
     * City
     */
    public UserBuilder city(String city) {
        user.setCity(city);
        return this;
    }

    /**
     * State/County/Province/Region
     */
    public UserBuilder area(String area) {
        user.setArea(area);
        return this;
    }

    /**
     * Zip Code
     */
    public UserBuilder zipCode(String zipCode) {
        user.setZipCode(zipCode);
        return this;
    }

    /**
     * Password
     */
    public UserBuilder password(String password) {
        user.setPassword(password);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public User build() {
        return user;
    }
}